plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation platform(project(':bom'))
    annotationProcessor platform(project(":bom"))
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.5.8')

    implementation project(':payment:api')
    implementation project(':payment:start')
}

jar {
    enabled = false
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-parameters')
}

tasks.register('integrationTest', Test) {
    description = 'Runs integration tests.'
    group = 'verification'
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    shouldRunAfter(tasks.test)
    useJUnitPlatform()
    testLogging {
        events 'passed', 'failed', 'skipped'
    }
}

tasks.check {
    dependsOn tasks.named('integrationTest')
}

test {
    useJUnitPlatform()
}