plugins {
    id 'java'
    id 'application'
    id 'jacoco-report-aggregation'
    id 'io.spring.dependency-management' version '1.1.7'
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:3.5.8'
    }
}

dependencies {
    implementation platform(project(":bom"))

    jacocoAggregation project(":store:api")
    jacocoAggregation project(":store:core")
    jacocoAggregation project(":store:start")

    jacocoAggregation project(":payment:api")
    jacocoAggregation project(":payment:start")

    implementation 'commons-io:commons-io'
}

jacoco {
    toolVersion = '0.8.11'
}

jar {
    enabled = false
}

testCodeCoverageReport {
    classDirectories.setFrom(
            files(classDirectories.files.collect { dir ->
                fileTree(dir: dir, exclude: [
                        '**/entity/**',
                        '**/dto/**',
                        '**/mappers/**'
                ])
            })
    )
}

tasks.named('check') {
    dependsOn tasks.named('testCodeCoverageReport', JacocoReport)
}
