plugins {
    id 'java'
    id 'jacoco'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openapi.generator' version '7.12.0'
}

jacoco {
    toolVersion = '0.8.11'
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:3.5.8'
    }
}

repositories { mavenCentral() }

dependencies {
    implementation platform(project(':bom'))

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui'
    implementation 'org.openapitools:jackson-databind-nullable'
    implementation 'org.hibernate.validator:hibernate-validator'
    implementation 'org.glassfish.expressly:expressly'


    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'io.projectreactor:reactor-test'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-parameters')
}

test { useJUnitPlatform() }

openApiGenerate {
    generatorName = "spring"
    library = "spring-boot"
    inputSpec = "${projectDir}/src/main/resources/openapi.yaml"
    outputDir = "${buildDir}/generated-sources/openapi"
    apiPackage = "io.github.habatoo.payment.api"
    modelPackage = "io.github.habatoo.payment.model"
    invokerPackage = "io.github.habatoo.payment.invoker"
    validateSpec = false
    configOptions = [
            reactive                 : "true",
            interfaceOnly            : "true",
            dateLibrary              : "java8",
            useBeanValidation        : "true",
            generateSpringApplication: "false",
            useJakartaEe             : "true"
    ]
}

sourceSets.main.java.srcDirs += "$buildDir/generated-sources/openapi/src/main/java"
tasks.compileJava.dependsOn tasks.openApiGenerate

tasks.named("compileJava") {
    dependsOn("openApiGenerate")
}