spring:
  application:
    name: my-market-app-6
  profiles:
    active: dev
  web:
    cors:
      path-pattern: "/**"
      allowed-origin-patterns:
        - "http://localhost"
        - "http://127.0.0.1"
      allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 10s

application:
  redis-ttl-minutes: ${SPRING_REDIS_TTL:1}

server:
  port: ${SPRING_DATASOURCE_STORE_PORT:8080}

payment:
  url: http://localhost:${SPRING_DATASOURCE_PAYMENT_PORT:8081}