spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:12345/test
    user: test
    password: test
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: test
  web:
    cors:
      path-pattern: "/**"
      allowed-origin-patterns:
        - "http://localhost"
        - "http://127.0.0.1"
      allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

logging:
  level:
    org:
      testcontainers: DEBUG