spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///test
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
