plugins {
    id 'java'
    id 'jacoco'
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openapi.generator' version '7.12.0'
}

jacoco {
    toolVersion = '0.8.11'
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:3.5.8'
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation platform(project(':bom'))
    annotationProcessor platform(project(":bom"))
    implementation project(':payment:api')

    api 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter'
    annotationProcessor 'org.springframework.boot:spring-boot-autoconfigure-processor'

    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.hibernate.orm:hibernate-core'
    implementation 'org.liquibase:liquibase-core'

    implementation 'org.mapstruct:mapstruct'
    annotationProcessor 'org.mapstruct:mapstruct-processor'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui'
    implementation 'jakarta.validation:jakarta.validation-api'
    implementation 'jakarta.annotation:jakarta.annotation-api'
    implementation 'org.openapitools:jackson-databind-nullable'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.security:spring-security-oauth2-jose'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

    runtimeOnly 'org.postgresql:r2dbc-postgresql'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jar {
    enabled = true
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-parameters')
}

test {
    useJUnitPlatform()
}

openApiGenerate {
    generatorName = "java"
    library = "webclient"
    inputSpec = "${rootDir}/payment/api/src/main/resources/openapi.yaml"
    outputDir = "$buildDir/generated-sources/openapi"
    apiPackage = "io.github.habatoo.store.payment.api"
    modelPackage = "io.github.habatoo.store.payment.model"
    invokerPackage = "io.github.habatoo.store.payment.invoker"
    validateSpec = false
    configOptions = [
            dateLibrary        : "java8",
            useSpringWebClient : "true",
            interfaceOnly      : "false",
            useJakartaEe       : "true",
            openApiNullable    : "false"
    ]
}

sourceSets.main.java.srcDirs += "$buildDir/generated-sources/openapi/src/main/java"

tasks.compileJava.dependsOn(tasks.openApiGenerate)