plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
}

jacoco {
    toolVersion = '0.8.11'
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.8"
    }
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.5.8')
    implementation platform(project(':bom'))
    implementation project(':core')
    implementation project(':api')

    implementation 'org.springframework.boot:spring-boot-starter'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
}

jar {
    enabled = true
}

springBoot {
    mainClass = 'io.github.habatoo.Application'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-parameters')
}

test {
    useJUnitPlatform()
}