spring:
  profiles:
    active: dev

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}

  datasource:
    url: ${SPRING_DATASOURCE_JDBC_URL}
    username: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}

  liquibase:
    enabled: true
    url: ${SPRING_DATASOURCE_JDBC_URL}
    user: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

  web:
    cors:
      path-pattern: "/**"
      allowed-origin-patterns:
        - "http://localhost"
        - "http://127.0.0.1"
      allowed-methods: [ GET, POST, PUT, DELETE, OPTIONS ]
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600