spring:
  profiles:
    active: dev

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    enabled: true
    url: ${SPRING_LIQUIBASE_URL}
    user: ${SPRING_LIQUIBASE_USER}
    password: ${SPRING_LIQUIBASE_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-market-app
            client-secret: ${KEYCLOAK_SECRET}
            scope: openid, profile, email, roles
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_INTERNAL_URL}

            authorization-uri: ${KEYCLOAK_EXTERNAL_URL}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_INTERNAL_URL}/protocol/openid-connect/token
            jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/protocol/openid-connect/certs
            user-info-uri: ${KEYCLOAK_INTERNAL_URL}/protocol/openid-connect/userinfo
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL}

payment:
  url: http://${PAYMENT_SERVICE_HOST}:${SPRING_DATASOURCE_PAYMENT_PORT}

application:
  redis-ttl-minutes: ${SPRING_REDIS_TTL}
  balance: 1000